---
- name: fetch devstack git
  git: repo=https://github.com/openstack-dev/devstack dest=~/devstack

- name: configure local.conf
  copy: src=local.conf dest=~/devstack

- name: Run devstack
  command: ./stack.sh
  args:
      chdir: ~/devstack
