- name: Configure base system
  become: true
  block:
      - name: Fix hostname
        shell: |
            hostnamectl set-hostname {{ ansible_fqdn }}
            hostnamectl set-hostname --transient {{ ansible_fqdn }}
      - name: Fix /etc/hosts
        lineinfile:
            dest: /etc/hosts
            line: "127.0.0.1   {{ ansible_fqdn }} {{ ansible_hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4"
            regexp: "127.0.0.1"
