- name: Setup stack user
  become: true
  block:
      - name: Create stack group
        group:
            name: stack
            state: present
      - name: Create stack user
        user:
            create_home: yes
            generate_ssh_key: yes
            name: stack
            shell: "/bin/bash"
            state: present
      - name: Setup sudo for stack user
        shell: echo "stack ALL=(root) NOPASSWD:ALL" | tee -a /etc/sudoers.d/stack; chmod 0440 /etc/sudoers.d/stack
      - name: Setup tripleo directories
        file:
            path: "{{item}}"
            state: directory
            owner: stack
            group: stack
        with_items:
            - /home/stack/images
            - /home/stack/templates
            - /home/stack/templates/firstboot
            - /home/stack/logs
