---
- name: Create a user
  become: true
  block:
      - name: Create stack user
        user:
            name: stack
            state: present
      - name: sudosers no tty
        lineinfile:
            dest: /etc/sudoers
            state: absent
            regexp: 'Defaults\s+requiretty'
      - name: add users to sudoers
        lineinfile:
            dest: "/etc/sudoers"
            line: "stack ALL=(root) NOPASSWD:ALL"

- name: Setup tripleo directories
  become: true
  file:
      path: "{{item}}"
      state: directory
      owner: stack
      group: stack
  with_items:
      - /home/stack/images
      - /home/stack/templates
      - /home/stack/templates/firstboot
      - /home/stack/logs
